### ISSUE TITLE
HDE icon does not show on desktop right away

### ISSUE THREAD

**Issue by BC46** [ollieraikkonen/Freelancer-hd-edition-install-script#74]
![No icon](https://cdn.discordapp.com/attachments/873144025350295616/934106041686302771/unknown.png)
After installing, the shortcut icon doesn't show right away unless the user refreshes their Desktop manually.

**Comment by ollieraikkonen** [comment]
Yeah it will be because we dont copy the exe until after the shortcut is
made since the actual install technically happens in the post install step.
We cant change this since we need 7zip before the actual install.

To workaround this we could include the exe in the [Files] section, however
this would inflate the installer size by 2MB

**Comment by ollieraikkonen** [comment]
ChangesAssociations=yes
in the [Setup] section should sort this
